/**
 * POST /api/documents/:id/qa
 *   Body: { question: string }
 *
 * Retrieval-grounded Q&A. Returns answer + citations + confidence.
 */
import { NextRequest } from "next/server";
import { db } from "@/lib/db";
import { ok, fail } from "@/lib/api-response";
import { requireUserId } from "@/services/auth/session";
import { aiService, buildRetriever } from "@/services/ai";
import { chunkDocument } from "@/services/documents/chunker";
import { Errors } from "@/lib/errors";
import { rateLimit } from "@/lib/rate-limit";
import { z } from "zod";

export const runtime = "nodejs";
export const maxDuration = 60;

const BodySchema = z.object({
  question: z.string().min(3, "Question must be at least 3 characters").max(1000),
});

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const userId = await requireUserId();
    const { id } = await params;

    const doc = await db.document.findUnique({ where: { id } });
    if (!doc || doc.userId !== userId) throw Errors.notFound("Document");

    const rl = rateLimit(`qa:${userId}:${id}`, 20);
    if (!rl.ok) throw Errors.rateLimited();

    const json = await req.json();
    const parsed = BodySchema.safeParse(json);
    if (!parsed.success) {
      throw Errors.validation(parsed.error.issues[0]?.message ?? "Invalid input");
    }
    const { question } = parsed.data;

    // Chunk document + retrieve
    const chunks = chunkDocument(doc.textContent, undefined, { page: doc.pageCount ?? undefined });
    const retriever = buildRetriever(chunks);
    const retrieved = retriever.retrieve(question, 4, 0.05);

    if (retrieved.length === 0) {
      // No relevant context — return "insufficient" without AI call.
      return ok({
        answer: "Not found in the provided document.",
        citations: [],
        confidence: "insufficient" as const,
        followUpQuestions: [],
        disclaimer:
          "This answer is generated by AI based only on the uploaded document. It is not legal advice.",
      });
    }

    const { data, meta } = await aiService.answerQuestion(question, retrieved);

    // Persist user message + assistant response
    await db.qaMessage.create({
      data: {
        documentId: id,
        role: "user",
        content: question,
      },
    });
    await db.qaMessage.create({
      data: {
        documentId: id,
        role: "assistant",
        content: data.answer,
        citations: JSON.stringify(data.citations),
      },
    });

    return ok({ ...data, model: meta.model });
  } catch (err) {
    return fail(err);
  }
}
